# Generated by Django 4.1.7 on 2023-03-23 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Coleção')),
                ('nome_para_ordenacao', models.CharField(max_length=30, verbose_name='Nome para Ordenação')),
                ('prioridade_na_ordenacao', models.BooleanField(default=False, help_text='Caso ativado, irá agrupar os livros dessa coleção na ordem da prateleira no lugar do autor.', verbose_name='Prioritário na ordenação')),
            ],
            options={
                'verbose_name': 'Coleção',
                'verbose_name_plural': 'Coleções',
            },
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.editora', verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='estante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.estante', verbose_name='Estante'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.idioma', verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='livro',
            name='colecao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.colecao', verbose_name='Coleção'),
        ),
    ]
