# Generated by Django 4.1.7 on 2023-03-22 13:26

from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoria_editora_estante_idioma_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo')),
                ('isbn', isbn_field.fields.ISBNField(blank=True, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.categoria')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.editora')),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.estante')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.idioma')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
