# Generated by Django 4.1.7 on 2023-03-30 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='skoob_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuário no Skoob'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
            },
        ),
    ]
