# Generated by Django 4.1.7 on 2023-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(to='main.autor'),
        ),
    ]
