# Generated by Django 4.1.7 on 2023-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_livro_ano_livro_paginas_livro_sinopse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='data',
            field=models.DateField(verbose_name='Data de Leitura'),
        ),
    ]
