# Generated by Django 4.1.7 on 2023-03-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_autor_nacionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Coleção'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='estante',
            name='comodo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cômodo'),
        ),
        migrations.AlterField(
            model_name='estante',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
