# Generated by Django 4.1.7 on 2023-04-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_autor_options_alter_editora_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=100, verbose_name='Pessoa')),
                ('data_inicio', models.DateField(verbose_name='Data de Empréstimo')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['data_inicio', 'data_fim'],
            },
        ),
    ]
