# Generated by Django 4.1.7 on 2023-03-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_livro_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
