# Generated by Django 4.1.7 on 2023-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_autor_nome_alter_idioma_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['descricao'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='colecao',
            options={'ordering': ['descricao'], 'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'ordering': ['nome'], 'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='estante',
            options={'ordering': ['descricao'], 'verbose_name': 'Estante', 'verbose_name_plural': 'Estantes'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'ordering': ['nome'], 'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='autor',
            name='nome_ordenado',
            field=models.CharField(default='', max_length=100, verbose_name='Nome Ordenado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
