# Generated by Django 4.1.7 on 2023-04-14 20:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_livro_autores_secundarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nacionalidade',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Nacionalidade'),
        ),
    ]
