# Generated by Django 4.1.7 on 2023-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_configuracaosistema_steam_api_key_usuario_steam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='steam_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Usuário na Steam'),
        ),
    ]
