# Generated by Django 5.2.11 on 2026-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_livro_subtitulo_alter_livro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='skoob_authentication',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuário na Steam'),
        ),
    ]
