# Generated by Django 4.1.7 on 2023-04-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='loja',
            new_name='lojas',
        ),
        migrations.RenameField(
            model_name='jogo',
            old_name='plataforma',
            new_name='plataformas',
        ),
    ]
