# Generated by Django 4.1.7 on 2023-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_loja_jogo_lojas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='lojas',
            field=models.ManyToManyField(blank=True, related_name='jogos', to='games.loja', verbose_name='Lojas'),
        ),
    ]
