# Generated by Django 4.1.7 on 2023-04-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_jogo_lojas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='jogo',
            unique_together={('titulo', 'tipo')},
        ),
    ]
