# Generated by Django 4.2 on 2023-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_loja_nome_alter_plataforma_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='nao_existe_no_steam',
            field=models.BooleanField(default=False, help_text='Marque esse campo para evitar que se realize a busca no steam desse título', verbose_name='Não existe no steam'),
        ),
    ]
