# Generated by Django 4.2 on 2023-04-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_jogo_nao_existe_no_steam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('filha_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='games.franquia', verbose_name='Filha de')),
            ],
            options={
                'verbose_name': 'Franquia',
                'verbose_name_plural': 'Franquias',
                'ordering': ['nome'],
            },
        ),
    ]
