# Generated by Django 4.2 on 2023-04-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_franquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franquia',
            name='filha_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='filhos', to='games.franquia', verbose_name='Filha de'),
        ),
    ]
