# Generated by Django 4.2 on 2023-04-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_franquia_filha_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='franquias',
            field=models.ManyToManyField(blank=True, related_name='jogos', to='games.franquia', verbose_name='Franquias'),
        ),
    ]
