# Generated by Django 4.2.17 on 2025-01-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_jogo_possui_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='possui_port',
            field=models.BooleanField(default=False, verbose_name='Possui port no PortMaster pro Trimui'),
        ),
    ]
