# Generated by Django 4.2.28 on 2026-02-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_jogo_possui_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='quero_jogar',
            field=models.BooleanField(default=False, verbose_name='Quero jogar'),
        ),
    ]
